[project]
name = "mbarde.signups"
version = "1.0.0"
description = "Plone-Addon for dynamic event sign-ups"
authors = [{ name = "Matthias Barde" }]
readme = "README.md"
license = "GPL-2.0-only"
license-files = ["LICENSE.GPL", "LICENSE.rst"]
requires-python = ">=3.12"
classifiers = [
    "Environment :: Web Environment",
    "Framework :: Plone",
    "Framework :: Plone :: 6.0",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

dependencies = [
    "Plone",
    "collective.easyform",
]

[project.entry-points."z3c.autoinclude.plugin"]
target = "plone"

[build-system]
requires = ["setuptools>=65"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]
namespaces = true
include = ["mbarde.signups*"]

[tool.setuptools.package-data]
"mbarde.signups" = ["**/*"]

[tool.black]
line-length = 100
target-version = ["py312"]
